=== dev-v/cc/cc-report/src/main/java/com/cc/report/test/config/csv/csv.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
   pdf报表的xml文件的DTD描述文件
   其头部需使用下面的 DOCTYPE
   <!DOCTYPE report SYSTEM "csv.dtd">
 	fileName CDATA #REQUIRED
-->
<!ELEMENT report (filename,params?,sources?,page)>
<!ATTLIST report 
	type (xls|csv) "csv"
>

<!ELEMENT filename (#PCDATA)>
<!ATTLIST filename
	length CDATA #IMPLIED>

<!ELEMENT params (param*)>
<!ELEMENT param EMPTY>
<!-- 数据需使用的初始参数定义，可以在报表文件中写死，但外部传入一个同名的参数将覆盖xml文件中的值 -->
<!ATTLIST param
	name CDATA #REQUIRED
	value CDATA #IMPLIED>
<!ELEMENT sources (source+)>
<!ELEMENT source (sql|hibernate)>
<!ATTLIST source 
	name CDATA #REQUIRED
	type (sql|hibernate) "sql">
<!ELEMENT sql (fields)>
<!ATTLIST sql 
	value CDATA #REQUIRED>
<!ELEMENT fields (field+)>
<!ELEMENT field (#PCDATA|sql|hibernate)*>
<!ATTLIST field 
	name CDATA #REQUIRED>
<!ELEMENT hibernate (params?,fields?)>
<!ATTLIST hibernate
	dao CDATA #REQUIRED
	po CDATA #REQUIRED
	method CDATA #REQUIRED>
<!ELEMENT page (image*,table+)>
<!--        page属性            -->
<!ATTLIST page 
	align (left) "left"
	vAlign (middle) "middle"
	border (true) "true"
	borderType (thin) "thin"
	borderWeight CDATA "0.1"
	borderColor (black) "black"
	blackColor (white) "white"
	fontFamily (宋体) "宋体"
	fontStyle (normal) "normal"
	fontSize CDATA "10"
	fontColor (black) "black"
	width CDATA "595"
	height CDATA "842"
	ending CDATA "..."
	blank CDATA "-"
	margin CDATA "20"
			
	beginRow CDATA "0"
	beginCol CDATA "0"
	cols CDATA "0"
	pageType (a0|a1|a2|a3|a4|a5|a6|a7|a8|a9|a10|
				b0|b1|b2|b3|b4|b5|b6|b7|b8|b9|b10|
				arch_a|arch_b|arch_c|arch_d) "a4">
<!ELEMENT image EMPTY>
<!ATTLIST image
	beginx CDATA "0"
	beginy CDATA "0"
	endx CDATA #IMPLIED
	endy CDATA #IMPLIED
	transparence CDATA "50"
	transparenceLeft CDATA "50"
	transparenceRight CDATA "50"
	width CDATA "100"
	height CDATA "100"
	src CDATA #IMPLIED>
<!ELEMENT table (tr+)>
<!--table属性
	sourceType (normal|subtr) "normal"
	sourceTrIndex CDATA  #IMPLIED
-->
<!ATTLIST table 
	ending CDATA #IMPLIED
	blank CDATA #IMPLIED>
<!ELEMENT tr (td+)>
<!ATTLIST tr 
	complement (true|false) "true"
	ending CDATA #IMPLIED
	blank CDATA #IMPLIED
	source CDATA #IMPLIED>
<!ELEMENT td (#PCDATA|table|img|labels|label)*>
<!--        td属性           -->
<!ATTLIST td 
	ending CDATA #IMPLIED
	blank CDATA #IMPLIED
	width CDATA "100"
	height CDATA "20"
	
	combine (true|false) "false"
	begin CDATA #IMPLIED
	length CDATA #IMPLIED
	colSpan (1) "1"
	rowSpan (1) "1"
	field CDATA #IMPLIED>
<!ELEMENT img (#PCDATA)>
<!ATTLIST img 
	width CDATA "100"
	height CDATA "100"
	src CDATA #REQUIRED>
<!ELEMENT labels EMPTY>
<!ATTLIST labels
	sourceType (sources|parent) "sources"
	source CDATA #REQUIRED
	label CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT label (#PCDATA)>
<!ATTLIST label
	value CDATA #REQUIRED>

=== dev-v/cc/cc-report/src/main/java/com/cc/report/test/config/csv/csv.xml
<!DOCTYPE report SYSTEM "csv.dtd">
<report>
	<filename>防病毒软件运行信息统计报表${startDate}到${endDate}</filename>
	<params>
		<param name="startDate" value="00"/>
		<param name="endDate" value="11"/>
	</params>
	<sources>
		<source name="knowledgeClass">
			<sql value="select * from ITOM_KNOWLEDGE_CLASS">
				<fields>
					<field name="id"></field>
					<field name="name"></field>
				</fields>
			</sql>
		</source>
		<source name="knowledge">
			<sql value="select * from ITOM_KNOWLEDGE">
				<fields>
					<field name="subject"></field>
					<field name="keywords"></field>
					<field name="content"></field>
					<field name="id"></field>
					<field name="modifies">
						<sql value="
							select * from ITOM_KNOWLEDGE_MODIFY
							where knowledgeId=${id}">
							<fields>
								<field name="subject"></field>
								<field name="keywords"></field>
								<field name="content"></field>
								<field name="oldVersions"></field>
								<field name="knowledgeClassId"></field>
							</fields>
						</sql>
					</field>
				</fields>
			</sql>
		</source>
	</sources>
	
	<page fontSize="12" pageType="a4">
		<table>
			<!-- <tr>
				<td>时间段：${startDate}到${endDate}</td>
			</tr>
			<tr>
				<td>知识主题</td>
				<td>知识关键词</td>
				<td>
					<table>
						<tr>
							<td>修订记录</td>
						</tr>
						<tr>
							<td>版本号</td>
							<td>修订主题</td>
							<td>修订关键字</td>
							<td>分类</td>
						</tr>
					</table>
				</td>
				<td>知识内容</td>
			</tr> -->
			<tr source="${knowledge}">
				<td>${subject}</td>
				<td>${keywords}</td>
				<td>
					<table>
						<tr source="${modifies}">
							<td>${oldVersions}</td>
							<td>${subject}</td>
							<td>${keywords}</td>
							<td>${knowledgeClassId}
								<labels label="name" value="id" source="${knowledgeClass}"/>
							</td>
						</tr>
					</table>
				</td>
				<td>${content}</td>
			</tr>
		 </table>
	</page>
</report>

=== dev-v/cc/cc-report/src/main/resources/csv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report SYSTEM "dtd/csv.dtd" >
<report>
  <filename>测试报表</filename>
  <sources>
  	<source name="test">
  		<sql value="
  		SELECT r.*, s.dname as idpname, agent.id as agentid, agent.dname as agentname, 
  		supp.dname AS suppliername
		from dcontractbuy r 
		left join (select id, dname from dcontractsale) s
		on s.id = r.idp
        left join (select id, dname from dagent) agent
		on agent.id = r.dagent
        LEFT JOIN (SELECT id, dname FROM dsupplier) supp ON supp.id = r.idsupplier
		WHERE 1=1
		ORDER BY r.idx desc
  		">
  			<fields>
  				<field name="idpname"/>
  				<field name="agentid"/>
  				<field name="agentname"/>
  				<field name="suppliername"/>
  			</fields>
  		</sql>
  	</source>
  </sources>
  <page>
    <table>
      <tr>
      	<td>adfas
      	</td>
      	<td>adfas
      	</td>
      </tr>
      <tr>
      	<td>adfas
      	</td>
      	<td>adfas
      	</td>
      </tr>
      <tr>
        <td>
        	<table>
		     	<tr source="test">
			        <td field="idpname"/>
			        <td field="agentid"/>
			        <td field="agentname"/>
			        <td field="suppliername"/>
	       		</tr>
        	</table>
        </td>
        <td>
        	<table>
        		<tr>
        			<td>sadfasf</td>
        			<td>sadfasf</td>
        			<td>sadfasf</td>
        			<td>sadfasf</td>
        			<td>sadfasf</td>
        		</tr>
        	</table>
        </td>
      </tr>
    </table>
    
    <table>
    	<tr>
    		<td>aaaaaaaaaaaaaaa</td>
    	</tr>
    </table>
  </page>
</report>
